apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  name: kube-vip
  namespace: default
spec:
  containers:
  - command:
    - /kube-vip
    - service
    - --configMap
    - plndr-configmap
    - --arp
    - --interface
    - ens192
    - --log
    - "5"
    image: plndr/kube-vip:0.1.1
    name: kube-vip
    resources: {}
    securityContext:
      capabilities:
        add:
        - NET_ADMIN
  hostNetwork: true
status: {}
